### ISSUE TITLE
Send later / Reminder Issue

### ISSUE THREAD

**Issue by ganeshmn1** [Schibum/sndlatr#3]
1.Have tried Send later option - the email is sent at the scheduled time, but receiver receives the email time as the time at which it was scheduled. Pleasee fix it.

2.Reminder option does provide an option to remind on same day as of earlier & it does not have option to exclude the If conditions. Earlier it use to support remind on same day & also without if conditions. Please fix it.

**Comment by Schibum** [comment]
This repo is not maintained, see Readme. Please fork & fix there.
