### ISSUE TITLE
Signature

### ISSUE THREAD

**Issue by leonardocf83** [Schibum/sndlatr#5]
Why sndlatr is signing my e-mails?

This started last week.

**Comment by corychoy** [comment]
This started for me today. I am going to remove this extension from my computer till this is either optional or fixed

**Comment by Schibum** [comment]
This repository contains the original, open source SndLatr code and is intended for people who want to host it themselves. Up to my knowledge nobody is offering an extension in the Chrome Web Store based on that code as of today. The one in the Chrome Web Store with that name does not seem to have anything to do with this code anymore.
